export {default as Banner} from './Banner';
export {default as Blogs} from './Blogs';
export {default as Footer} from './Footer';
export {default as Header} from './Header';
export {default as Order} from './Order';
export {default as Roadmap} from './Roadmap';
export {default as Slider} from './Slider';
export {default as Subscribe} from './Subscribe';
export {default as Testimonials} from './Testimonials';